### ISSUE TITLE
System Probe Config fails when enabling network_config

### ISSUE THREAD

**Issue by lognarly** [DataDog/ansible-datadog#330]
When trying to enable NPM on Linux systems, I am getting a failure when trying to set the following:

network_config:
  enabled: true

Role being called by playbook. Everything else works as needed.

```
- name: Install Datadog Agent - JAVA
  include_role:
    name: datadog.datadog
    tasks_from: main
  vars:
    datadog_config: "{{ datadog_agent_config_java }}"
    system_probe_config:
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
    network_config:
      enabled: true
    datadog_checks: "{{ datadog_java_config }}"
```
Error:
```
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'enabled'\n\nThe error appears to be in '/Users/logan/.ansible/roles/datadog.datadog/tasks/agent-linux.yml': line 95, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set system probe enabled\n  ^ here\n"}
```

The flag used to be:
```
system_probe_config:
  enabled: true
```

Using ansible [core 2.11.0b3]

**Comment by bkabrda** [comment]
Hi 👋 it seems that the README change introduced in https://github.com/DataDog/ansible-datadog/pull/326 made the docs really confusing. Basically for linux at this point, you should keep

```
  system_probe_config:
      enabled: true
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
```

We'll be reverting PR #326, as there are more issues with it. We'll release 4.7.1 with it reverted and when we fix everything properly, we'll release a new version with Windows NPM support and all related updates.

**Comment by lognarly** [comment]
This contrasts with the DD documentation here. So structuring the system-probe.yaml file as you've done should work the same as what is shown in your docs?

https://docs.datadoghq.com/network_monitoring/performance/setup/?tab=agent#setup

**Comment by bkabrda** [comment]
@lognarly thanks to the PR #326 we actually identified an issue with this. `system_probe_config` would only work with agent < 7.24.0 and for newer agents, `network_config` is required. We will fix this and update the docs accordingly for the upcoming release.

**Comment by lognarly** [comment]
Yeah we are installing the latest, so this is required. Is there a time estimation on when the release will be made to allow us to rollout NPM using the parameters required for agents > 7.24.0?

**Comment by bkabrda** [comment]
@lognarly we don't have an estimate yet, but I'll keep you posted about the progress. We already #332 opened which is one of the fixes we'll need to get in - so hopefully it won't take long.

**Comment by lognarly** [comment]
Thank you!

**Comment by bkabrda** [comment]
4.7.1 is now released, reverting #326: https://github.com/DataDog/ansible-datadog/releases/tag/4.7.1

I'll update/close this issue when we implement and release the fixes we talked about.

**Comment by lognarly** [comment]
How can I go about updating this module only on my Ansible system?

**Comment by bkabrda** [comment]
@lognarly would `ansible-galaxy install -f datadog.datadog,4.7.1` work for you?

**Comment by lognarly** [comment]
That worked, thank you!

**Comment by bkabrda** [comment]
Hey 👋 we've just released version 4.8.0 which re-adds windows NPM and thus should fix your problems. See https://github.com/DataDog/ansible-datadog#system-probe for updated information on sysprobe/network_config setup.

I'm closing this issue. If you have any problems, feel free to open a new one. Thanks!
