### ISSUE TITLE
TASK [Datadog.datadog : Create system-probe configuration file] Failure

### ISSUE THREAD

**Issue by tasktop-teho** [DataDog/ansible-datadog#360]
Since Jinja2 version 3 is released in May 11, the backward compatible `indentfirst` has been [removed](https://github.com/pallets/jinja/pull/1136/commits/b0015c72d5acbf93b9d99a1ce6167889338db85b#diff-d3eeabaeac0164a4aa81d32a82599f1a5c90aca43eb52117d387ae393e9431f7). This breaks system-probe.yaml.j2 . We are getting:
````
fatal: [packer]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on (# Managed by Ansible

{% if system_probe_config is defined and system_probe_config|length > 0 -%}
system_probe_config:
{# The "first" option is only supported by jinja 2.10+
  which is not present on older systems (CentOS 7, Debian 8, etc.)
  Using the equivalent option "indentfirst" will work with
  all currently existing jinja 2 versions (as of this comment, up to 2.10).
  TODO: when future versions of Jinja are released, check that
  indentfirst is still supported.
 #}
{% filter indent(width=2, indentfirst=True) %}
{{ system_probe_config | to_nice_yaml }}
{% endfilter %}
{% endif %}
): do_indent() got an unexpected keyword argument 'indentfirst'"}
````

Which corresponds to https://github.com/DataDog/ansible-datadog/issues/229

The `indentfirst` was introduced in https://github.com/DataDog/ansible-datadog/pull/240, and we knew the drop of `indentfirst` was comming https://github.com/DataDog/ansible-datadog/pull/240#issuecomment-726327045
